"""empty message

Revision ID: 1974200d95b7
Revises: c0f73e2b08f2
Create Date: 2022-05-16 23:33:00.448788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1974200d95b7'
down_revision = 'c0f73e2b08f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('home', sa.String(length=250), nullable=True))
    op.add_column('characters', sa.Column('ships', sa.String(length=250), nullable=True))
    op.drop_column('characters', 'ships_used')
    op.drop_column('characters', 'home_planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('home_planet', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('characters', sa.Column('ships_used', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('characters', 'ships')
    op.drop_column('characters', 'home')
    # ### end Alembic commands ###
