"""empty message

Revision ID: 1fbe18b38f91
Revises: 1974200d95b7
Create Date: 2022-05-17 22:43:05.559626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbe18b38f91'
down_revision = '1974200d95b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('homeplanet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'characters', 'planets', ['homeplanet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'homeplanet_id')
    # ### end Alembic commands ###
