"""empty message

Revision ID: eff6afe01dbe
Revises: 71ccdfbbf6a5
Create Date: 2022-05-19 16:49:24.895423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eff6afe01dbe'
down_revision = '71ccdfbbf6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('hair', sa.String(length=250), nullable=True))
    op.drop_column('characters', 'home')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('home', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('characters', 'hair')
    # ### end Alembic commands ###
